# Generated by Django 5.2.8 on 2025-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacear',
            name='marcador',
            field=models.CharField(choices=[('hiro', 'Hiro Marker'), ('kanji', 'Kanji Marker')], default='hiro', max_length=50),
        ),
    ]
