# Generated by Django 5.2.8 on 2025-11-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visors_app', '0002_interfacear_marcador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacear',
            name='marcador',
            field=models.CharField(choices=[('hiro', 'Hiro Marker'), ('kanji', 'Kanji Marker')], default='hiro', max_length=200),
        ),
        migrations.AlterField(
            model_name='interfacear',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
